[versions]

[libraries]

[bundles]

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:7.0.8"
publishOnCentral = "org.danilopianini.publish-on-central:9.1.9"
taskTree = "com.dorongold.task-tree:4.0.1"
